### ISSUE TITLE
渲染效果不对劲

### ISSUE THREAD

**Issue by Freedomisgood** [stevenjoezhang/hexo-filter-mathjax#5]
<details><summary>Content of debug log</summary>
<pre>
---
title: Latex测试
date: 2019-11-26 21:34:07
mathjax: true
tags:
---

$UCB1(S_{i})=\overline{V_{i}}+c \sqrt{\frac{\log N}{n_{i}}}, c=2$

$$UCB1(S_{i})=\overline{V_{i}}+c \sqrt{\frac{\log N}{n_{i}}}, c=2$$

$\frac{Q(v_{i})}{N(v_{i})}$

$$\frac{Q(v_{i})}{N(v_{i})}$$

$\overline{V_{i}}$

$$\overline{V_{i}}$$

$\frac{1}{4}$

$$\frac{1}{4}$$

$\epsilon_0$

$$\epsilon_0$$

$\epsilon_{0}$

$$\epsilon_{0}$$
</pre>
</details>
但我的页面显示是这样的，有的消失不了，epsilon0可以显示，但是前面的代码并没有消失
![渲染效果](http://chuantu.xyz/t6/703/1574776456x1033347913.jpg)

**Comment by Freedomisgood** [comment]
<details><summary>_config.yml配置</summary>
<pre>

mathjax:
  single_dollars: true
  cjk_char_width: 16
  svg: true
</pre>
</details>

<details><summary>我的博客文章</summary>
<pre>
---
title: Latex测试
date: 2019-11-26 21:34:07
mathjax: true
tags:
---
$UCB1(S_{i})=\overline{V_{i}}+c \sqrt{\frac{\log N}{n_{i}}}, c=2$


$$UCB1(S_{i})=\overline{V_{i}}+c \sqrt{\frac{\log N}{n_{i}}}, c=2$$


$\frac{Q(v_{i})}{N(v_{i})}$


$$\frac{Q(v_{i})}{N(v_{i})}$$


$\overline{V_{i}}$


$$\overline{V_{i}}$$


$\frac{1}{4}$


$$\frac{1}{4}$$


$\epsilon_0$


$$\epsilon_0$$


$\epsilon_{0}$


$$\epsilon_{0}$$
</pre>
但我的页面显示是这样的，有的消失不了，epsilon0可以显示，但是前面的代码并没有消失 
[</details>](http://chuantu.xyz/t6/703/1574776456x1033347913.jpg)

**Comment by Freedomisgood** [comment]
<details><summary>_config.yml配置</summary>
<pre>
mathjax:

single_dollars: true

cjk_char_width: 16

svg: true


</pre>
</details>
<details><summary>我的博客文章</summary>
<pre>

---
title: Latex测试
date: 2019-11-26 21:34:07
mathjax: true
tags:
---
$UCB1(S_{i})=\overline{V_{i}}+c \sqrt{\frac{\log N}{n_{i}}}, c=2$
$$UCB1(S_{i})=\overline{V_{i}}+c \sqrt{\frac{\log N}{n_{i}}}, c=2$$


$\frac{Q(v_{i})}{N(v_{i})}$


$$\frac{Q(v_{i})}{N(v_{i})}$$


$\overline{V_{i}}$


$$\overline{V_{i}}$$


$\frac{1}{4}$


$$\frac{1}{4}$$


$\epsilon_0$


$$\epsilon_0$$


$\epsilon_{0}$


$$\epsilon_{0}$$
</pre>
</details>


但我的页面显示是这样的，有的消失不了，epsilon0可以显示，但是前面的代码并没有消失
[显示效果](http://chuantu.xyz/t6/703/1574776456x1033347913.jpg)

**Comment by stevenjoezhang** [comment]
源码没有问题。看上去您安装了katex插件，请将它们全部卸载。
