### ISSUE TITLE
插入内容的时候插入的 css 样式导致摘要不对

### ISSUE THREAD

**Issue by songouyang** [stevenjoezhang/hexo-filter-mathjax#9]
![image](https://user-images.githubusercontent.com/16632254/72198488-6fcae600-3469-11ea-9e2b-af8f8d2d36b2.png)
![image](https://user-images.githubusercontent.com/16632254/72198491-79ece480-3469-11ea-9a85-d03aea037860.png)
还插入了多余的 rss 链接
![image](https://user-images.githubusercontent.com/16632254/72198500-96891c80-3469-11ea-82a2-c1e5d7e40217.png)
仓库：https://github.com/songouyang/notes/
预览：https://hexo-54fff.firebaseapp.com/

**Comment by stevenjoezhang** [comment]
请在 Hexo 的 `_config.yml` 中设置 `description`。

本插件没有任何与 RSS 相关的功能，请进一步控制变量以确定问题的原因。

总而言之，您所提出的问题均与本插件无关，这个 Issue 先关闭了。

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/stevenjoezhang/hexo-filter-mathjax/commit/09d3f7cc4f5243f6243993635dc6bec6c77c3dac
